//
//  ViewUserPresenterTests.swift
//  ClanManager
//
//  Created by Jeffrey Wu on 2017-01-13.
//  Copyright (c) 2017 Cheeseonhead. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import Quick
@testable import ClanManager
import Nimble

class ViewUserPresenterTests: QuickSpec
{
    override func spec()
    {
        var presenter: ViewUserPresenter!
        var outputSpy: OutputSpy!

        beforeEach
        {
            present = ViewUserPresenter()
            outputSpy = OutputSpy()
        }

        describe("Fetch User")
        {

        }
    }
}

fileprivate class OutputSpy: ViewUserPresenterOutput
{
    var displayUserCalled = false
    var viewUser_fetchUser_viewModel: ViewUser.FetchUser.ViewModel!

    func displayUser(viewModel: ViewUser.FetchUser.ViewModel)
    {
        displayUserCalled = true
        viewUser_fetchUser_viewModel = viewModel
    }
}
