//
//  ViewUserWorkerTests.swift
//  ClanManager
//
//  Created by Jeffrey Wu on 2017-01-13.
//  Copyright (c) 2017 Cheeseonhead. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

@testable import ClanManager
import XCTest

class ViewUserWorkerTests: XCTestCase
{
  // MARK: - Subject under test
  
  var userWorker: UserWorker!
  
  // MARK: - Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    setupViewUserWorker()
  }
  
  override func tearDown()
  {
    super.tearDown()
  }
  
  // MARK: - Test setup
  
  func setupViewUserWorker()
  {
      userWorker = UserWorker(userStore: UserMemStoreSpy())
  }
  
  // MARK: - Test doubles
  
  // MARK: - Tests
  
  func testSomething()
  {
    // Given
    
    // When
    
    // Then
  }
}


fileprivate class UserMemStoreSpy : UserMemStore
{
    var fetchUserCalled = false

    override func fetchUser(completionHandler: (_: User) -> Void)
    {
        fetchUserCalled = true
        let oneSecondAfter = DispatchTime.now() + 1
        DispatchQueue.main.asyncAfter(deadline: oneSecondAfter, execute: {
            completionHandler(User())
        })
    }
}
