//
//  ViewUserViewControllerTests.swift
//  ClanManager
//
//  Created by Jeffrey Wu on 2017-01-13.
//  Copyright (c) 2017 Cheeseonhead. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

@testable import ClanManager
import XCTest
import Quick
import Nimble

class ViewUserViewControllerTests: QuickSpec
{
    override func spec()
    {
        var viewController: ViewUserViewController!
        var outputSpy: OutputSpy!
        var window: UIWindow!

        beforeEach
        {
            window = UIWindow()
            outputSpy = OutputSpy()
            viewController = self.createViewController()
            viewController.output = outputSpy

            self.loadView(window: window, viewController: viewController)
        }

        describe("Event Load")
        {
            it("should have dispatched a request to output")
            {
                expect(outputSpy.fetchUserCalled).to(beTrue())
            }
        }

        describe("Display Fetch User")
        {
            var defaultViewModel = ViewUser.FetchUser.ViewModel()

            describe("Name Label")
            {
                it("should have same text as view model")
                {
                    defaultViewModel.name = "Just a test name"

                    viewController.displayUser(viewModel: defaultViewModel)

                    expect(viewController.nameLabel.text).to(equal(defaultViewModel.name))
                }
            }

            describe("Town Hall Label")
            {
                it("should have same text as view model")
                {
                    defaultViewModel.townHallDescription = "Toooooooownhall 10"

                    viewController.displayUser(viewModel: defaultViewModel)

                    expect(viewController.townHallLabel.text).to(equal(defaultViewModel.townHallDescription))
                }
            }

            describe("Experience Label")
            {
                it("should have the same text as view model")
                {
                    defaultViewModel.experience = "128"

                    viewController.displayUser(viewModel: defaultViewModel)

                    expect(viewController.experienceLabel.text).to(equal(defaultViewModel.experience))
                }
            }

            describe("League Icon")
            {
                var imageViewSpy: UIImageViewSpy!

                beforeEach
                {
                    imageViewSpy = UIImageViewSpy()
                    viewController.leagueIconImage = imageViewSpy
                }

                context("URL string is valid")
                {
                    beforeEach
                    {
                        defaultViewModel.leagueIconURL = "https://api-assets.clashofclans.com/leagues/288/Y6CveuHmPM_oiOic2Yet0rYL9AFRYW0WA0u2e44-YbM.png"
                    }

                    it("should call loadImageFrom")
                    {
                        viewController.displayUser(viewModel: defaultViewModel)

                        expect(imageViewSpy.loadFromURLCalled).to(beTrue())
                    }

                    it("should pass the correct URL")
                    {
                        viewController.displayUser(viewModel: defaultViewModel)

                        expect(imageViewSpy.loadURLGiven.absoluteString).to(equal(defaultViewModel.leagueIconURL))
                    }
                }
            }

            describe("League Name")
            {
                it("should have the same text as the view model")
                {
                    defaultViewModel.leagueName = "Gold II"

                    viewController.displayUser(viewModel: defaultViewModel)

                    expect(viewController.leagueNameLabel.text).to(equal(defaultViewModel.leagueName))
                }
            }

            describe("Trophies Label")
            {
                it("should have the same text as the view model")
                {
                    defaultViewModel.trophyDescription = "Trohpies: 12392"

                    viewController.displayUser(viewModel: defaultViewModel)

                    expect(viewController.trophiesLabel.text).to(equal(defaultViewModel.trophyDescription))
                }
            }
        }
    }

    func createViewController() -> ViewUserViewController
    {
        let bundle = Bundle.main
        let storyboard = UIStoryboard(name: "ViewUser", bundle: bundle)
        return storyboard.instantiateViewController(withIdentifier: "ViewUserViewController") as! ViewUserViewController
    }

    func loadView(window: UIWindow, viewController: UIViewController)
    {
        window.addSubview(viewController.view)
        RunLoop.current.run(until: Date())
    }
}

fileprivate class OutputSpy: ViewUserViewControllerOutput
{
    var fetchUserCalled = false

    func fetchUser(request _: ViewUser.FetchUser.Request)
    {
        fetchUserCalled = true
    }
}

fileprivate class UIImageViewSpy: UIImageView
{
    var loadFromURLCalled = false
    var loadURLGiven: URL!

    override func loadFromURL(url: URL)
    {
        loadFromURLCalled = true
        loadURLGiven = url
    }
}
