//
//  EditSettingsPresenter.swift
//  ClanManager
//
//  Created by Jeffrey Wu on 2017-01-17.
//  Copyright (c) 2017 Cheeseonhead. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//

import UIKit

protocol EditSettingsPresenterInput {
    
}

protocol EditSettingsPresenterOutput: class {
    
}

class EditSettingsPresenter: EditSettingsPresenterInput {
    
    weak var output: EditSettingsPresenterOutput!
    
    // MARK: Presentation logic
    
}
