//
//  EditSettingsViewController.swift
//  ClanManager
//
//  Created by Jeffrey Wu on 2017-01-17.
//  Copyright (c) 2017 Cheeseonhead. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//

import UIKit

protocol EditSettingsViewControllerInput
{
    func displaySettings(viewModel: EditSettings.FetchSettings.ViewModel)
}

protocol EditSettingsViewControllerOutput
{
    func fetchSettings(request: EditSettings.FetchSettings.Request)
}

class EditSettingsViewController: UIViewController, EditSettingsViewControllerInput
{

    var output: EditSettingsViewControllerOutput!
    var router: EditSettingsRouter!

    @IBOutlet weak var playerTagTextField: UITextField!
    @IBOutlet weak var saveButton: UIButton!

    // MARK: Object lifecycle

    override func awakeFromNib()
    {
        super.awakeFromNib()
        EditSettingsConfigurator.sharedInstance.configure(viewController: self)
    }

    // MARK: View lifecycle

    override func viewDidLoad()
    {
        super.viewDidLoad()
        fetchSettingsOnLoad()
    }

    // MARK: Event handling

    func fetchSettingsOnLoad()
    {
    }

    @IBAction func saveButtonPressed(_: UIButton)
    {
    }

    // MARK: Display logic

    func displaySettings(viewModel _: EditSettings.FetchSettings.ViewModel)
    {
    }
}

// This should be on configurator but for some reason storyboard doesn't detect ViewController's name if placed there
extension EditSettingsViewController: EditSettingsPresenterOutput
{
    override func prepare(for segue: UIStoryboardSegue, sender: Any?)
    {
        router.passDataToNextScene(for: segue)
    }
}
