//
//  EditSettingsViewController.swift
//  ClanManager
//
//  Created by Jeffrey Wu on 2017-01-17.
//  Copyright (c) 2017 Cheeseonhead. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//

import UIKit

protocol EditSettingsViewControllerInput
{
    func displaySettings(viewModel: EditSettings.FetchSettings.ViewModel)
    func displayStoreSettings(viewModel: EditSettings.StoreSettings.ViewModel)
}

protocol EditSettingsViewControllerOutput
{
    func fetchSettings(request: EditSettings.FetchSettings.Request)
    func storeSettings(request: EditSettings.StoreSettings.Request)
}

class EditSettingsViewController: UIViewController, EditSettingsViewControllerInput
{

    var output: EditSettingsViewControllerOutput!
    var router: EditSettingsRouter!

    @IBOutlet weak var playerTagTextField: UITextField!
    @IBOutlet weak var saveButton: UIButton!
    @IBOutlet weak var scrollView: UIScrollView!
    @IBOutlet weak var contentView: UIView!

    // MARK: Object lifecycle

    override func awakeFromNib()
    {
        super.awakeFromNib()
        EditSettingsConfigurator.sharedInstance.configure(viewController: self)
    }

    // MARK: View lifecycle

    override func viewDidLoad()
    {
        super.viewDidLoad()
        fetchSettingsOnLoad()

        NotificationCenter.default.addObserver(self, selector: #selector(keyboardWasShown(notification:)), name: NSNotification.Name.UIKeyboardWillChangeFrame, object: nil)
        NotificationCenter.default.addObserver(self, selector: #selector(keyboardWasHidden(notification:)), name: NSNotification.Name.UIKeyboardWillHide, object: nil)
    }

    override func viewDidLayoutSubviews()
    {
        super.viewDidLayoutSubviews()
        self.updateContentOffset()
    }

    func keyboardWasShown(notification: NSNotification)
    {
        var info = notification.userInfo!
        let keyboardSize = (info[UIKeyboardFrameEndUserInfoKey] as? NSValue)?.cgRectValue.size

        var temp = self.scrollView.frame
        temp.size.height = self.view.frame.size.height - (keyboardSize?.height)!
        self.scrollView.frame = temp

        self.updateContentOffset()
    }

    func keyboardWasHidden(notification _: NSNotification)
    {
        self.scrollView.frame = self.view.bounds

        self.updateContentOffset()
    }

    func updateContentOffset()
    {
        let topOffset = (self.scrollView.frame.size.height - self.contentView.frame.size.height) / 2
        self.scrollView.contentInset = UIEdgeInsets(top: topOffset, left: 0, bottom: 0, right: 0)
    }

    // MARK: Event handling

    func fetchSettingsOnLoad()
    {
        output.fetchSettings(request: EditSettings.FetchSettings.Request())
    }

    @IBAction func saveButtonPressed(_: UIButton)
    {
        var request = EditSettings.StoreSettings.Request()
        request.playerTag = self.playerTagTextField.text!

        output.storeSettings(request: request)
    }

    // MARK: Display logic

    func displaySettings(viewModel: EditSettings.FetchSettings.ViewModel)
    {
        self.playerTagTextField.text = viewModel.currentPlayerTag
    }

    func displayStoreSettings(viewModel: EditSettings.StoreSettings.ViewModel)
    {
        if viewModel.isReadyToNavigate
        {
            router.dismissController()
        }
    }

    override var prefersStatusBarHidden: Bool
    {
        return true
    }
}
