//
//  EditSettingsInteractor.swift
//  ClanManager
//
//  Created by Jeffrey Wu on 2017-01-17.
//  Copyright (c) 2017 Cheeseonhead. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//

import UIKit

protocol EditSettingsInteractorInput {
    
}

protocol EditSettingsInteractorOutput {
    
}

protocol EditSettingsDataSource {
    
}

protocol EditSettingsDataDestination {
    
}

class EditSettingsInteractor: EditSettingsInteractorInput, EditSettingsDataSource, EditSettingsDataDestination {
    
    var output: EditSettingsInteractorOutput!
    
    // MARK: Business logic
    

}
