//
//  EditSettingsRouter.swift
//  ClanManager
//
//  Created by Jeffrey Wu on 2017-01-17.
//  Copyright (c) 2017 Cheeseonhead. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//

import UIKit

protocol EditSettingsRouterInput
{
    func dismissController()
}

protocol EditSettingsRouterDataSource: class {}

protocol EditSettingsRouterDataDestination: class {}

class EditSettingsRouter: EditSettingsRouterInput
{
    weak var viewController: EditSettingsViewController!
    private weak var dataSource: EditSettingsRouterDataSource!
    weak var dataDestination: EditSettingsRouterDataDestination!

    init(viewController: EditSettingsViewController, dataSource: EditSettingsRouterDataSource, dataDestination: EditSettingsRouterDataDestination)
    {
        self.viewController = viewController
        self.dataSource = dataSource
        self.dataDestination = dataDestination
    }

    // MARK: Navigation

    func dismissController()
    {

    }

    // MARK: Communication
}
