//
//  EditSettingsConfigurator.swift
//  ClanManager
//
//  Created by Jeffrey Wu on 2017-01-17.
//  Copyright (c) 2017 Cheeseonhead. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//

import UIKit

class EditSettingsConfigurator
{
    // MARK: Object lifecycle

    static let sharedInstance = EditSettingsConfigurator()

    private init() {}

    // MARK: Configuration

    func configure(viewController: EditSettingsViewController)
    {

        let presenter = EditSettingsPresenter()
        presenter.output = viewController

        let interactor = EditSettingsInteractor()
        interactor.output = presenter

        let router = EditSettingsRouter(viewController: viewController, dataSource: interactor, dataDestination: interactor)

        viewController.output = interactor
        viewController.router = router
    }
}

extension EditSettingsViewController: EditSettingsPresenterOutput {}

extension EditSettingsInteractor: EditSettingsViewControllerOutput, EditSettingsRouterDataSource, EditSettingsRouterDataDestination {}

extension EditSettingsPresenter: EditSettingsInteractorOutput {}
