//
//  EditSettingsPresenter.swift
//  ClanManager
//
//  Created by Jeffrey Wu on 2017-01-17.
//  Copyright (c) 2017 Cheeseonhead. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//

import UIKit

protocol EditSettingsPresenterInput
{
    func presentSettings(response: EditSettings.FetchSettings.Response)
    func presentStoreSettingsResult(response: EditSettings.StoreSettings.Response)
}

protocol EditSettingsPresenterOutput: class
{
    func displaySettings(viewModel: EditSettings.FetchSettings.ViewModel)
    func displayStoreSettings(viewModel: EditSettings.StoreSettings.ViewModel)
}

class EditSettingsPresenter: EditSettingsPresenterInput
{

    weak var output: EditSettingsPresenterOutput!

    // MARK: Presentation logic

    func presentSettings(response: EditSettings.FetchSettings.Response)
    {
        let viewModel = EditSettings.FetchSettings.ViewModel(currentPlayerTag: response.currentPlayerTag)
        output.displaySettings(viewModel: viewModel)
    }

    func presentStoreSettingsResult(response: EditSettings.StoreSettings.Response)
    {
        var viewModel = EditSettings.StoreSettings.ViewModel()

        viewModel.isReadyToNavigate = response.success
        viewModel.errorLabelVisible = !response.success

        switch response.playerTagValidation {
        case .containsSpaces:
            viewModel.errorLabelText = "Player tags should not contain spaces."
            break
        case .empty:
            viewModel.errorLabelText = "Player tag cannot be empty."
            break
        default:
            break
        }

        output.displayStoreSettings(viewModel: viewModel)
    }
}
