//
//  EditSettingsRouter.swift
//  ClanManager
//
//  Created by Jeffrey Wu on 2017-01-17.
//  Copyright (c) 2017 Cheeseonhead. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//

import UIKit

protocol EditSettingsRouterInput {
    
}

protocol EditSettingsRouterDataSource:class {
    
}

protocol EditSettingsRouterDataDestination:class {
    
}

class EditSettingsRouter: EditSettingsRouterInput {
    
    weak var viewController:EditSettingsViewController!
    weak private var dataSource:EditSettingsRouterDataSource!
    weak var dataDestination:EditSettingsRouterDataDestination!
    
    init(viewController:EditSettingsViewController, dataSource:EditSettingsRouterDataSource, dataDestination:EditSettingsRouterDataDestination) {
        self.viewController = viewController
        self.dataSource = dataSource
        self.dataDestination = dataDestination
    }
    
    // MARK: Navigation
    
    // MARK: Communication
    
    func passDataToNextScene(for segue: UIStoryboardSegue) {
        // NOTE: Teach the router which scenes it can communicate with
        
    }
}
