//
//  EditSettingsViewController.swift
//  ClanManager
//
//  Created by Jeffrey Wu on 2017-01-17.
//  Copyright (c) 2017 Cheeseonhead. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//

import UIKit

protocol EditSettingsViewControllerInput {
    
}

protocol EditSettingsViewControllerOutput {
    func fetchSettings(request: EditSettings.FetchSettings.Request)
}

class EditSettingsViewController: UIViewController, EditSettingsViewControllerInput {
    
    var output: EditSettingsViewControllerOutput!
    var router: EditSettingsRouter!
    
    // MARK: Object lifecycle
    
    override func awakeFromNib() {
        super.awakeFromNib()
        EditSettingsConfigurator.sharedInstance.configure(viewController: self)
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        fetchSettingsOnLoad()
    }
    
    // MARK: Event handling
    
    func fetchSettingsOnLoad()
    {
    }
    
    // MARK: Display logic
    
}

//This should be on configurator but for some reason storyboard doesn't detect ViewController's name if placed there
extension EditSettingsViewController: EditSettingsPresenterOutput {
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        router.passDataToNextScene(for: segue)
    }
}
