#!/bin/sh

# prepare the formatter
swiftformat

# format code
git status --porcelain | grep -e '^[AM]\(.*\).swift$' | cut -c 3- | while read line; do
  swiftformat --indent 4 --allman false --wraparguments disabled --removelines disabled --wrapelements disabled --header ignore --insertlines disabled --empty void --ranges spaced --trimwhitespace always --linebreaks lf --commas always --comments indent --ifdef indent --hexliterals uppercase --semicolons inline ${line};
  git add $line;
done
