//
//  ViewUserInteractor.swift
//  ClanManager
//
//  Created by Jeffrey Wu on 2017-01-13.
//  Copyright (c) 2017 Cheeseonhead. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//

import UIKit

protocol ViewUserInteractorInput {
    func fetchUser(request: ViewUser_FetchUser_Request)
}

protocol ViewUserInteractorOutput {
    func presentUser(response: ViewUser_PresentUser_Response)
}

protocol ViewUserDataSource {
    
}

protocol ViewUserDataDestination {
    
}

class ViewUserInteractor: ViewUserInteractorInput, ViewUserDataSource, ViewUserDataDestination {
    
    var output: ViewUserInteractorOutput!
    
    // MARK: Business logic
    
    func fetchUser(request: ViewUser_FetchUser_Request)
    {
    }
}
