//
//  ViewUserRouter.swift
//  ClanManager
//
//  Created by Jeffrey Wu on 2017-01-13.
//  Copyright (c) 2017 Cheeseonhead. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//

import UIKit

protocol ViewUserRouterInput {
    
}

protocol ViewUserRouterDataSource:class {
    
}

protocol ViewUserRouterDataDestination:class {
    
}

class ViewUserRouter: ViewUserRouterInput {
    
    weak var viewController:ViewUserViewController!
    weak private var dataSource:ViewUserRouterDataSource!
    weak var dataDestination:ViewUserRouterDataDestination!
    
    init(viewController:ViewUserViewController, dataSource:ViewUserRouterDataSource, dataDestination:ViewUserRouterDataDestination) {
        self.viewController = viewController
        self.dataSource = dataSource
        self.dataDestination = dataDestination
    }
    
    // MARK: Navigation
    
    // MARK: Communication
    
    func passDataToNextScene(for segue: UIStoryboardSegue) {
        // NOTE: Teach the router which scenes it can communicate with
        
    }
}
