//
//  ViewUserConfigurator.swift
//  ClanManager
//
//  Created by Jeffrey Wu on 2017-01-13.
//  Copyright (c) 2017 Cheeseonhead. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//

import UIKit

class ViewUserConfigurator
{
    // MARK: Object lifecycle

    static let sharedInstance = ViewUserConfigurator()

    private init() {}

    // MARK: Configuration

    func configure(viewController: ViewUserViewController)
    {
        let presenter = ViewUserPresenter()
        presenter.output = viewController

        let interactor = ViewUserInteractor()
        interactor.output = presenter

        let router = ViewUserRouter(viewController: viewController, dataSource: interactor, dataDestination: interactor)

        viewController.output = interactor
        viewController.router = router
        viewController.dataReceiver = interactor
    }
}

extension ViewUserInteractor: ViewUserViewControllerOutput, ViewUserRouterDataProvider, ViewUserRouterDataReceiver {}

extension ViewUserPresenter: ViewUserInteractorOutput {}

extension ViewUserRouter: ViewUserViewControllerRouter {}

extension ViewUserViewController: ViewUserPresenterOutput {}
