//
//  ViewUserRouter.swift
//  ClanManager
//
//  Created by Jeffrey Wu on 2017-01-13.
//  Copyright (c) 2017 Cheeseonhead. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//

import UIKit

protocol ViewUserRouterInput {}

protocol ViewUserRouterDataProvider: class {}

protocol ViewUserRouterDataReceiver: class
{
    var playerTag: String! { get set }
}

class ViewUserRouter: ViewUserRouterInput
{
    weak var viewController: UIViewController!
    private weak var dataSource: ViewUserRouterDataProvider!
    weak var dataDestination: ViewUserRouterDataReceiver!

    init(viewController: UIViewController, dataSource: ViewUserRouterDataProvider, dataDestination: ViewUserRouterDataReceiver)
    {
        self.viewController = viewController
        self.dataSource = dataSource
        self.dataDestination = dataDestination
    }
}
