//
//  ViewUserPresenter.swift
//  ClanManager
//
//  Created by Jeffrey Wu on 2017-01-13.
//  Copyright (c) 2017 Cheeseonhead. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//

import UIKit

protocol ViewUserPresenterInput
{
    func presentUser(response: ViewUser.FetchUser.Response)
}

protocol ViewUserPresenterOutput: class
{
    func displayUser(viewModel: ViewUser.FetchUser.ViewModel)
}

class ViewUserPresenter: ViewUserPresenterInput
{

    weak var output: ViewUserPresenterOutput!

    // MARK: Presentation logic

    func presentUser(response: ViewUser.FetchUser.Response)
    {
        var viewModel = ViewUser.FetchUser.ViewModel()

        viewModel.name = response.firstName + " " + response.lastName
        viewModel.leagueIconURL = "https://api-assets.clashofclans.com/leagues/288/Y6CveuHmPM_oiOic2Yet0rYL9AFRYW0WA0u2e44-YbM.png"
        viewModel.townHallDescription = String.localizedStringWithFormat(NSLocalizedString("TownHall_Level_Description", comment: ""), response.townHallLevel)
        viewModel.leagueName = response.leagueName
        viewModel.experience = "\(response.experienceLevel)"
        viewModel.trophyDescription = String.localizedStringWithFormat(NSLocalizedString("Trophies_Description", comment: ""), response.trophyCount)

        output.displayUser(viewModel: viewModel)
    }
}
