//
//  ViewUserModels.swift
//  ClanManager
//
//  Created by Jeffrey Wu on 2017-01-13.
//  Copyright (c) 2017 Cheeseonhead. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//
//  Type "usecase" for some magic!

import UIKit

struct ViewUser
{
    struct FetchUser
    {

        struct Request
        {

        }

        struct Response
        {
            var firstName: String
            var lastName: String
            var townHallLevel: Int
        }

        struct ViewModel
        {

        }
    }
}
