//
//  ViewUserPresenter.swift
//  ClanManager
//
//  Created by Jeffrey Wu on 2017-01-13.
//  Copyright (c) 2017 Cheeseonhead. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//

import UIKit

protocol ViewUserPresenterInput
{
    func presentUser(response: ViewUser.FetchUser.Response)
}

protocol ViewUserPresenterOutput: class
{
    func displayUser(viewModel: ViewUser.FetchUser.ViewModel)
}

class ViewUserPresenter: ViewUserPresenterInput
{

    weak var output: ViewUserPresenterOutput!

    // MARK: Presentation logic

    func presentUser(response: ViewUser.FetchUser.Response)
    {
        let name = response.firstName + " " + response.lastName
        let info = "Town Hall level \(response.townHallLevel)"

        var viewModel = ViewUser.FetchUser.ViewModel()
        output.displayUser(viewModel: viewModel)
    }
}
