//
//  EditSettingsViewControllerTests.swift
//  ClanManager
//
//  Created by Jeffrey Wu on 2017-01-17.
//  Copyright (c) 2017 Cheeseonhead. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

@testable import ClanManager
import XCTest

class EditSettingsViewControllerTests: XCTestCase
{
  // MARK: - Subject under test
  
  var sut: EditSettingsViewController!
  var window: UIWindow!
  
  // MARK: - Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    window = UIWindow()
    setupEditSettingsViewController()
  }
  
  override func tearDown()
  {
    window = nil
    super.tearDown()
  }
  
  // MARK: - Test setup
  
  func setupEditSettingsViewController()
  {
    let bundle = Bundle.main
    let storyboard = UIStoryboard(name: "EditSettings", bundle: bundle)
    sut = storyboard.instantiateViewController(withIdentifier: "EditSettingsViewController") as! EditSettingsViewController
  }
  
  func loadView()
  {
    window.addSubview(sut.view)
    RunLoop.current.run(until: Date())
  }
  
  // MARK: - Test doubles
  
  // MARK: - Tests
  
  func testSomething()
  {
    // Given
    
    // When
    
    // Then
  }
}
