//
//  TabControlModels.swift
//  ClanManager
//
//  Created by Jeffrey Wu on 2017-01-22.
//  Copyright (c) 2017 Cheeseonhead. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//
//  Type "usecase" for some magic!

import UIKit

struct TabControl
{
    struct FetchSettings
    {
        struct Request
        {
        }
        struct Response: Equatable
        {
            var currentPlayerTag: String = ""

            static func ==(lhs: Response, rhs: Response) -> Bool
            {
                return lhs.currentPlayerTag == rhs.currentPlayerTag
            }
        }
        struct ViewModel
        {
            var playerTag: String = ""
        }
    }
}
