//
//  TabControlRouter.swift
//  ClanManager
//
//  Created by Jeffrey Wu on 2017-01-22.
//  Copyright (c) 2017 Cheeseonhead. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//

import UIKit

protocol TabControlRouterInput
{

}

protocol TabControlRouterDataSource: class
{
    func getPlayerTagToDisplay() -> String
}

protocol TabControlRouterDataDestination: class
{
    var displayPlayerTag: String { get set }
}

class TabControlRouter: TabControlRouterInput
{

    weak var viewController: TabControlViewController!
    private weak var dataSource: TabControlRouterDataSource!
    weak var dataDestination: TabControlRouterDataDestination!

    init(viewController: TabControlViewController, dataSource: TabControlRouterDataSource, dataDestination: TabControlRouterDataDestination)
    {
        self.viewController = viewController
        self.dataSource = dataSource
        self.dataDestination = dataDestination
    }

    // MARK: Navigation

    // MARK: Communication

    func passDataToNextScene(for segue: UIStoryboardSegue)
    {
        // NOTE: Teach the router which scenes it can communicate with

    }
}
