//
//  TabControlPresenter.swift
//  ClanManager
//
//  Created by Jeffrey Wu on 2017-01-22.
//  Copyright (c) 2017 Cheeseonhead. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//

import UIKit

protocol TabControlPresenterInput
{

}

protocol TabControlPresenterOutput: class
{

}

class TabControlPresenter: TabControlPresenterInput
{

    weak var output: TabControlPresenterOutput!

    // MARK: Presentation logic

}
