//
//  TabControlViewController.swift
//  ClanManager
//
//  Created by Jeffrey Wu on 2017-01-22.
//  Copyright (c) 2017 Cheeseonhead. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//

import UIKit

protocol TabControlViewControllerInput {}

protocol TabControlViewControllerOutput {}

protocol TabControlViewControllerRouter: Router
{
    func openSettingsViewController()
}

class TabControlViewController: UITabBarController, TabControlViewControllerInput
{

    var output: TabControlViewControllerOutput!
    var router: TabControlViewControllerRouter!

    // MARK: Object lifecycle

    override func awakeFromNib()
    {
        super.awakeFromNib()
        TabControlConfigurator.sharedInstance.configure(viewController: self)
    }

    // MARK: View lifecycle

    override func viewDidLoad()
    {
        super.viewDidLoad()
    }

    // MARK: Event handling

    // MARK: Display logic

}
