//
//  TabControlInteractor.swift
//  ClanManager
//
//  Created by Jeffrey Wu on 2017-01-22.
//  Copyright (c) 2017 Cheeseonhead. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//

import UIKit

protocol TabControlInteractorInput
{

}

protocol TabControlInteractorOutput
{

}

protocol TabControlDataSource
{

}

protocol TabControlDataDestination
{

}

class TabControlInteractor: TabControlInteractorInput, TabControlDataSource, TabControlDataDestination
{

    var output: TabControlInteractorOutput!

    // MARK: Business logic

}
