//
//  TabControlInteractor.swift
//  ClanManager
//
//  Created by Jeffrey Wu on 2017-01-22.
//  Copyright (c) 2017 Cheeseonhead. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//

import UIKit

protocol TabControlInteractorInput
{
    func fetchSettings(request: TabControl.FetchSettings.Request)
}

protocol TabControlInteractorOutput
{
    func presentSettings(response: TabControl.FetchSettings.Response)
}

protocol TabControlDataProvider
{
    var currentPlayerTag: String? { get }
}

protocol TabControlDataReceiver {}

class TabControlInteractor: TabControlInteractorInput, TabControlDataProvider, TabControlDataReceiver
{
    var output: TabControlInteractorOutput!
    var sessionWorker: SessionWorker! = SessionWorker(store: SessionMemStore())

    var currentPlayerTag: String?

    // MARK: Business logic

    func fetchSettings(request _: TabControl.FetchSettings.Request)
    {
        sessionWorker.fetchSettings
        { settings in
            guard let settings = settings else
            {
                self.output.presentSettings(response: TabControl.FetchSettings.Response())
                return
            }

            self.currentPlayerTag = settings.currentPlayerTag

            let response = TabControl.FetchSettings.Response(currentPlayerTag: settings.currentPlayerTag)
            self.output.presentSettings(response: response)
        }
    }
}
