//
//  TabControlInteractor.swift
//  ClanManager
//
//  Created by Jeffrey Wu on 2017-01-22.
//  Copyright (c) 2017 Cheeseonhead. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//

import UIKit

protocol TabControlInteractorInput
{
    func fetchSettings(request: TabControl.FetchSettings.Request)
}

protocol TabControlInteractorOutput {}

protocol TabControlDataProvider
{
    var displayPlayerTag: String! { get }
}

protocol TabControlDataReceiver {}

class TabControlInteractor: TabControlInteractorInput, TabControlDataProvider, TabControlDataReceiver
{
    var output: TabControlInteractorOutput!

    var displayPlayerTag: String!

    // MARK: Business logic

    func fetchSettings(request _: TabControl.FetchSettings.Request)
    {

    }
}
