//
//  TabControlRouter.swift
//  ClanManager
//
//  Created by Jeffrey Wu on 2017-01-22.
//  Copyright (c) 2017 Cheeseonhead. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//

import UIKit

protocol TabControlRouterInput
{

}

protocol TabControlRouterDataProvider: class
{
    var displayPlayerTag: String! { get }
}

protocol TabControlRouterDataReceiver: class
{
}

class TabControlRouter: TabControlRouterInput
{

    weak var viewController: UIViewController!
    private weak var dataSource: TabControlRouterDataProvider!
    weak var dataDestination: TabControlRouterDataReceiver!

    init(viewController: UIViewController, dataSource: TabControlRouterDataProvider, dataDestination: TabControlRouterDataReceiver)
    {
        self.viewController = viewController
        self.dataSource = dataSource
        self.dataDestination = dataDestination
    }

    // MARK: Navigation

    func openSettingsViewController()
    {

    }

    // MARK: Communication

    func passDataToNextScene(for segue: UIStoryboardSegue)
    {
        // NOTE: Teach the router which scenes it can communicate with

    }
}
