//
//  TabControlPresenter.swift
//  ClanManager
//
//  Created by Jeffrey Wu on 2017-01-22.
//  Copyright (c) 2017 Cheeseonhead. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//

import UIKit

protocol TabControlPresenterInput
{
    func presentSettings(response: TabControl.FetchSettings.Response)
}

protocol TabControlPresenterOutput: class
{
    func displaySettings(viewModel: TabControl.FetchSettings.ViewModel)
}

class TabControlPresenter: TabControlPresenterInput
{
    weak var output: TabControlPresenterOutput!

    func presentSettings(response: TabControl.FetchSettings.Response)
    {
        var viewModel = TabControl.FetchSettings.ViewModel()
        if response.currentPlayerTag != nil
        {
            viewModel.playerTag = response.currentPlayerTag!
        }

        output.displaySettings(viewModel: viewModel)
    }
}
